/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Ai DIY",
  "tagline": "Documentation for Full Stack & AI Engineering",
  "favicon": "img/favicon.svg",
  "url": "https://docs.yiw.me",
  "baseUrl": "/",
  "trailingSlash": true,
  "organizationName": "YiWang24",
  "projectName": "portfolio",
  "deploymentBranch": "main",
  "onBrokenLinks": "ignore",
  "customFields": {
    "frontendUrl": "http://localhost:3000",
    "backendUrl": "http://localhost:8001"
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/wy/projects/AiDIY/sidebars.ts",
          "editUrl": "https://github.com/YiWang24/portfolio/tree/main/docs/",
          "remarkPlugins": [
            [
              null,
              {
                "sync": true
              }
            ],
            [
              null,
              {
                "strict": false
              }
            ]
          ],
          "rehypePlugins": [
            null
          ]
        },
        "blog": {
          "showReadingTime": true,
          "authorsMapPath": "authors.yml",
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "copyright": "Copyright © 2026 Yi Wang. Built with Docusaurus."
          },
          "editUrl": "https://github.com/YiWang24/portfolio/tree/main/docs/",
          "remarkPlugins": [
            [
              null,
              {
                "sync": true
              }
            ],
            [
              null,
              {
                "strict": false
              }
            ]
          ],
          "rehypePlugins": [
            null
          ]
        },
        "theme": {
          "customCss": "/home/wy/projects/AiDIY/src/css/custom.css"
        }
      }
    ]
  ],
  "themes": [
    "@docusaurus/theme-live-codeblock",
    "@docusaurus/theme-mermaid"
  ],
  "plugins": [
    "docusaurus-plugin-image-zoom",
    "docusaurus-plugin-copy-page-button"
  ],
  "markdown": {
    "format": "mdx",
    "mermaid": true,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  },
  "themeConfig": {
    "image": "img/opengraph-image.png",
    "navbar": {
      "title": "Ai DIY",
      "logo": {
        "alt": "Yi Wang Logo",
        "src": "img/favicon.svg",
        "href": "https://www.yiw.me",
        "target": "_self"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "csSidebar",
          "position": "left",
          "label": "CS Core"
        },
        {
          "type": "docSidebar",
          "sidebarId": "aiSidebar",
          "position": "left",
          "label": "AI & Agents"
        },
        {
          "type": "docSidebar",
          "sidebarId": "engineeringSidebar",
          "position": "left",
          "label": "Engineering"
        },
        {
          "type": "docSidebar",
          "sidebarId": "projectsSidebar",
          "position": "left",
          "label": "Case Studies"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "href": "https://www.yiw.me",
          "label": "Portfolio",
          "position": "right"
        },
        {
          "href": "https://github.com/YiWang24/AiDIY",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "CS Core",
          "items": [
            {
              "label": "Algorithms & DS",
              "to": "/docs/cs/algorithms"
            },
            {
              "label": "System Design",
              "to": "/docs/cs/system-design"
            },
            {
              "label": "Database Internals",
              "to": "/docs/cs/database"
            },
            {
              "label": "Network & OS",
              "to": "/docs/cs/network-os"
            }
          ]
        },
        {
          "title": "AI & Agents",
          "items": [
            {
              "label": "LLM Fundamentals",
              "to": "/docs/ai/llm-fundamentals"
            },
            {
              "label": "RAG Systems",
              "to": "/docs/ai/rag"
            },
            {
              "label": "Agentic Workflows",
              "to": "/docs/ai/agents"
            },
            {
              "label": "Spring AI",
              "to": "/docs/ai/spring-ai"
            }
          ]
        },
        {
          "title": "Engineering",
          "items": [
            {
              "label": "Backend (Java)",
              "to": "/docs/engineering/backend"
            },
            {
              "label": "Frontend",
              "to": "/docs/engineering/frontend"
            },
            {
              "label": "DevOps & Cloud",
              "to": "/docs/engineering/devops"
            },
            {
              "label": "Dev Tools",
              "to": "/docs/engineering/tools"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Case Studies",
              "to": "/docs/projects"
            },
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/YiWang24/portfolio"
            },
            {
              "label": "Main Site",
              "href": "https://www.yiw.me"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 Yi Wang. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "java",
        "typescript",
        "tsx",
        "bash",
        "python",
        "json",
        "yaml",
        "docker",
        "sql",
        "graphql",
        "go",
        "rust",
        "c",
        "cpp",
        "csharp",
        "kotlin",
        "swift",
        "ruby",
        "php",
        "scala",
        "haskell",
        "diff",
        "git",
        "nginx",
        "toml",
        "ini",
        "makefile"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "error-next-line"
        },
        {
          "className": "code-block-success-line",
          "line": "success-next-line"
        }
      ]
    },
    "zoom": {
      "selector": ".markdown img",
      "background": {
        "light": "rgb(255, 255, 255)",
        "dark": "rgb(20, 20, 20)"
      }
    },
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    },
    "mermaid": {
      "theme": {
        "light": "neutral",
        "dark": "dark"
      },
      "options": {}
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
